
/* File generated by gen_cfile.py. Should not be modified. */

#include "Slave1.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 test_Value = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 Slave1_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 Slave1_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 Slave1_iam_a_slave = 1;

TIMER_HANDLE Slave1_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 Slave1_obj1000 = 0x0;	/* 0 */
                    subindex Slave1_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Slave1_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 Slave1_obj1001 = 0x0;	/* 0 */
                    subindex Slave1_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave1_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 Slave1_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 Slave1_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex Slave1_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Slave1_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 Slave1_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 Slave1_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 Slave1_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 Slave1_obj100D = 0x0;   /* 0 */

/* index 0x1010 :   Store parameters. */
                    UNS8 Slave1_highestSubIndex_obj1010 = 127; /* number of subindex - 1*/
                    UNS32 Slave1_obj1010_Save_All_Parameters = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Communication_Parameters = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Application_Parameters = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_1 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_2 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_3 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_4 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_5 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_6 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_7 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_8 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_9 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_10 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_11 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_12 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_13 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_14 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_15 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_16 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_17 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_18 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_19 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_20 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_21 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_22 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_23 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_24 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_25 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_26 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_27 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_28 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_29 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_30 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_31 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_32 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_33 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_34 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_35 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_36 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_37 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_38 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_39 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_40 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_41 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_42 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_43 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_44 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_45 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_46 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_47 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_48 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_49 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_50 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_51 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_52 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_53 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_54 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_55 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_56 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_57 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_58 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_59 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_60 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_61 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_62 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_63 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_64 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_65 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_66 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_67 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_68 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_69 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_70 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_71 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_72 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_73 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_74 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_75 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_76 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_77 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_78 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_79 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_80 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_81 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_82 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_83 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_84 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_85 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_86 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_87 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_88 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_89 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_90 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_91 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_92 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_93 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_94 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_95 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_96 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_97 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_98 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_99 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_100 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_101 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_102 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_103 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_104 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_105 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_106 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_107 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_108 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_109 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_110 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_111 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_112 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_113 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_114 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_115 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_116 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_117 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_118 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_119 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_120 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_121 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_122 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_123 = 0x0;	/* 0 */
                    UNS32 Slave1_obj1010_Save_Manufacturer_Parameters_124 = 0x0;	/* 0 */
                    subindex Slave1_Index1010[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1010, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_All_Parameters, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Communication_Parameters, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Application_Parameters, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_1, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_2, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_3, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_4, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_5, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_6, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_7, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_8, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_9, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_10, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_11, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_12, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_13, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_14, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_15, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_16, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_17, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_18, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_19, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_20, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_21, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_22, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_23, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_24, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_25, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_26, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_27, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_28, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_29, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_30, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_31, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_32, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_33, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_34, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_35, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_36, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_37, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_38, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_39, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_40, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_41, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_42, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_43, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_44, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_45, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_46, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_47, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_48, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_49, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_50, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_51, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_52, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_53, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_54, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_55, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_56, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_57, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_58, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_59, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_60, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_61, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_62, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_63, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_64, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_65, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_66, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_67, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_68, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_69, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_70, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_71, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_72, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_73, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_74, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_75, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_76, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_77, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_78, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_79, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_80, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_81, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_82, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_83, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_84, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_85, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_86, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_87, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_88, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_89, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_90, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_91, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_92, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_93, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_94, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_95, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_96, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_97, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_98, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_99, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_100, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_101, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_102, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_103, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_104, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_105, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_106, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_107, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_108, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_109, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_110, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_111, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_112, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_113, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_114, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_115, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_116, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_117, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_118, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_119, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_120, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_121, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_122, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_123, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1010_Save_Manufacturer_Parameters_124, NULL }
                     };

/* index 0x1014 :   Emergency COB ID */
                    UNS32 Slave1_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 Slave1_highestSubIndex_obj1016 = 0;
                    UNS32 Slave1_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 Slave1_obj1017 = 0x3E8;	/* 1000 */
                    subindex Slave1_Index1017[] = 
                     {
                       { RW|TO_BE_SAVE, uint16, sizeof (UNS16), (void*)&Slave1_obj1017, NULL }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 Slave1_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 Slave1_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 Slave1_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 Slave1_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 Slave1_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex Slave1_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Slave1_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Slave1_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Slave1_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Slave1_obj1018_Serial_Number, NULL }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 Slave1_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 Slave1_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 Slave1_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex Slave1_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1200, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Slave1_obj1200_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Slave1_obj1200_COB_ID_Server_to_Client_Transmit_SDO, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 Slave1_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 Slave1_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 Slave1_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Slave1_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Slave1_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Slave1_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 Slave1_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex Slave1_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave1_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave1_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 Slave1_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 Slave1_obj1401_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 Slave1_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Slave1_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Slave1_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Slave1_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 Slave1_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex Slave1_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave1_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave1_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1401_SYNC_start_value, NULL }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 Slave1_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 Slave1_obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 Slave1_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Slave1_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Slave1_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Slave1_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 Slave1_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex Slave1_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1402, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1402_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1402_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave1_obj1402_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1402_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave1_obj1402_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1402_SYNC_start_value, NULL }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 Slave1_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 Slave1_obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 Slave1_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Slave1_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Slave1_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Slave1_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 Slave1_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex Slave1_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1403, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1403_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1403_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave1_obj1403_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1403_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave1_obj1403_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1403_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 Slave1_highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 Slave1_obj1600[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Slave1_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1600[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1600[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1600[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1600[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1600[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1600[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1600[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1600[7], NULL }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 Slave1_highestSubIndex_obj1601 = 8; /* number of subindex - 1*/
                    UNS32 Slave1_obj1601[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Slave1_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1601[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1601[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1601[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1601[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1601[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1601[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1601[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1601[7], NULL }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 Slave1_highestSubIndex_obj1602 = 8; /* number of subindex - 1*/
                    UNS32 Slave1_obj1602[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Slave1_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1602, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1602[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1602[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1602[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1602[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1602[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1602[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1602[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1602[7], NULL }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 Slave1_highestSubIndex_obj1603 = 8; /* number of subindex - 1*/
                    UNS32 Slave1_obj1603[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Slave1_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1603, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1603[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1603[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1603[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1603[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1603[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1603[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1603[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1603[7], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 Slave1_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 Slave1_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 Slave1_obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Slave1_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Slave1_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Slave1_obj1800_Event_Timer = 0x1F4;	/* 500 */
                    UNS8 Slave1_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex Slave1_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave1_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave1_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 Slave1_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 Slave1_obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 Slave1_obj1801_Transmission_Type = 0x4;	/* 4 */
                    UNS16 Slave1_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Slave1_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Slave1_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 Slave1_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    subindex Slave1_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1801, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1801_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1801_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave1_obj1801_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1801_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave1_obj1801_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1801_SYNC_start_value, NULL }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 Slave1_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 Slave1_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 Slave1_obj1802_Transmission_Type = 0x4;	/* 4 */
                    UNS16 Slave1_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Slave1_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Slave1_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 Slave1_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    subindex Slave1_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1802, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1802_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1802_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave1_obj1802_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1802_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave1_obj1802_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1802_SYNC_start_value, NULL }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 Slave1_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 Slave1_obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 Slave1_obj1803_Transmission_Type = 0x4;	/* 4 */
                    UNS16 Slave1_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Slave1_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Slave1_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 Slave1_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    subindex Slave1_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1803, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1803_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1803_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave1_obj1803_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1803_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Slave1_obj1803_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_obj1803_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 Slave1_highestSubIndex_obj1A00 = 8; /* number of subindex - 1*/
                    UNS32 Slave1_obj1A00[] = 
                    {
                      0x20000008,	/* 536870920 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Slave1_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A00[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A00[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A00[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A00[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A00[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A00[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A00[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A00[7], NULL }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 Slave1_highestSubIndex_obj1A01 = 8; /* number of subindex - 1*/
                    UNS32 Slave1_obj1A01[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Slave1_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1A01, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A01[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A01[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A01[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A01[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A01[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A01[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A01[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A01[7], NULL }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 Slave1_highestSubIndex_obj1A02 = 8; /* number of subindex - 1*/
                    UNS32 Slave1_obj1A02[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Slave1_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1A02, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A02[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A02[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A02[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A02[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A02[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A02[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A02[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A02[7], NULL }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 Slave1_highestSubIndex_obj1A03 = 8; /* number of subindex - 1*/
                    UNS32 Slave1_obj1A03[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Slave1_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Slave1_highestSubIndex_obj1A03, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A03[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A03[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A03[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A03[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A03[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A03[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A03[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Slave1_obj1A03[7], NULL }
                     };

/* index 0x2000 :   Mapped variable test_Value */
                    subindex Slave1_Index2000[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&test_Value, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable Slave1_objdict[] = 
{
  { (subindex*)Slave1_Index1000,sizeof(Slave1_Index1000)/sizeof(Slave1_Index1000[0]), 0x1000},
  { (subindex*)Slave1_Index1001,sizeof(Slave1_Index1001)/sizeof(Slave1_Index1001[0]), 0x1001},
  { (subindex*)Slave1_Index1010,sizeof(Slave1_Index1010)/sizeof(Slave1_Index1010[0]), 0x1010},
  { (subindex*)Slave1_Index1017,sizeof(Slave1_Index1017)/sizeof(Slave1_Index1017[0]), 0x1017},
  { (subindex*)Slave1_Index1018,sizeof(Slave1_Index1018)/sizeof(Slave1_Index1018[0]), 0x1018},
  { (subindex*)Slave1_Index1200,sizeof(Slave1_Index1200)/sizeof(Slave1_Index1200[0]), 0x1200},
  { (subindex*)Slave1_Index1400,sizeof(Slave1_Index1400)/sizeof(Slave1_Index1400[0]), 0x1400},
  { (subindex*)Slave1_Index1401,sizeof(Slave1_Index1401)/sizeof(Slave1_Index1401[0]), 0x1401},
  { (subindex*)Slave1_Index1402,sizeof(Slave1_Index1402)/sizeof(Slave1_Index1402[0]), 0x1402},
  { (subindex*)Slave1_Index1403,sizeof(Slave1_Index1403)/sizeof(Slave1_Index1403[0]), 0x1403},
  { (subindex*)Slave1_Index1600,sizeof(Slave1_Index1600)/sizeof(Slave1_Index1600[0]), 0x1600},
  { (subindex*)Slave1_Index1601,sizeof(Slave1_Index1601)/sizeof(Slave1_Index1601[0]), 0x1601},
  { (subindex*)Slave1_Index1602,sizeof(Slave1_Index1602)/sizeof(Slave1_Index1602[0]), 0x1602},
  { (subindex*)Slave1_Index1603,sizeof(Slave1_Index1603)/sizeof(Slave1_Index1603[0]), 0x1603},
  { (subindex*)Slave1_Index1800,sizeof(Slave1_Index1800)/sizeof(Slave1_Index1800[0]), 0x1800},
  { (subindex*)Slave1_Index1801,sizeof(Slave1_Index1801)/sizeof(Slave1_Index1801[0]), 0x1801},
  { (subindex*)Slave1_Index1802,sizeof(Slave1_Index1802)/sizeof(Slave1_Index1802[0]), 0x1802},
  { (subindex*)Slave1_Index1803,sizeof(Slave1_Index1803)/sizeof(Slave1_Index1803[0]), 0x1803},
  { (subindex*)Slave1_Index1A00,sizeof(Slave1_Index1A00)/sizeof(Slave1_Index1A00[0]), 0x1A00},
  { (subindex*)Slave1_Index1A01,sizeof(Slave1_Index1A01)/sizeof(Slave1_Index1A01[0]), 0x1A01},
  { (subindex*)Slave1_Index1A02,sizeof(Slave1_Index1A02)/sizeof(Slave1_Index1A02[0]), 0x1A02},
  { (subindex*)Slave1_Index1A03,sizeof(Slave1_Index1A03)/sizeof(Slave1_Index1A03[0]), 0x1A03},
  { (subindex*)Slave1_Index2000,sizeof(Slave1_Index2000)/sizeof(Slave1_Index2000[0]), 0x2000},
};

const indextable * Slave1_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1010: i = 2;break;
		case 0x1017: i = 3;break;
		case 0x1018: i = 4;break;
		case 0x1200: i = 5;break;
		case 0x1400: i = 6;break;
		case 0x1401: i = 7;break;
		case 0x1402: i = 8;break;
		case 0x1403: i = 9;break;
		case 0x1600: i = 10;break;
		case 0x1601: i = 11;break;
		case 0x1602: i = 12;break;
		case 0x1603: i = 13;break;
		case 0x1800: i = 14;break;
		case 0x1801: i = 15;break;
		case 0x1802: i = 16;break;
		case 0x1803: i = 17;break;
		case 0x1A00: i = 18;break;
		case 0x1A01: i = 19;break;
		case 0x1A02: i = 20;break;
		case 0x1A03: i = 21;break;
		case 0x2000: i = 22;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &Slave1_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status Slave1_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index Slave1_firstIndex = {
  5, /* SDO_SVR */
  0, /* SDO_CLT */
  6, /* PDO_RCV */
  10, /* PDO_RCV_MAP */
  14, /* PDO_TRS */
  18 /* PDO_TRS_MAP */
};

const quick_index Slave1_lastIndex = {
  5, /* SDO_SVR */
  0, /* SDO_CLT */
  9, /* PDO_RCV */
  13, /* PDO_RCV_MAP */
  17, /* PDO_TRS */
  21 /* PDO_TRS_MAP */
};

const UNS16 Slave1_ObjdictSize = sizeof(Slave1_objdict)/sizeof(Slave1_objdict[0]); 

CO_Data Slave1_Data = CANOPEN_NODE_DATA_INITIALIZER(Slave1);

